# Site settings
title: Bryan D. Sandoval´s CV
name: Bryan Daniel Sandoval Gaytan

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 #- title: Blog
  # url: https://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/danisg99
 #- title: StackOverflow
  # url: https://stackoverflow.com/users/258813/rhinds
 #- title: DZone
  # url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/bryan-daniel-sandoval-gaytan-b85821149

abilities:
 - Spanish (First Language)
 - Leadership
 - Organization
 - Critical Thinking
 - Inquirer
 - Problem Solver
 
#Any buzzword skills you want to include
skills:
 - MATLAB
 - FUSION 360
 - AUTOCAD
 - PID Controllers
 - Assembly Language for Microcontrollers
 - Microsoft Office
 - Basic GD&T
 - Basic ROS
 - Basic python
 - Basic LabVIEW
 - Basic SOLIDWORKS
 - Basic PROTEUS

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
# blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Research Engineer
   start: 2019
   end: Ongoing
   employer: Centro de Investigación y Desarrollo de Tecnología Digital - Instituto Politécnico Nacional (CITEDI - IPN)
   description: Working on a research project to develop a Neural Network for the prediction of Glass Transition Temperatures for Amorphous Alloys.
 - title: Member of Existential Robotics Laboratory (ERL)
   start: 2019
   end: 2019
   employer: Existential Robotics Laboratory (ERL)
   description: ENLACE 2019 Summer Research Program at UCSD.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2021
   subject: Mechatronics Engineering
   school: Centro de Enseñanza Técnica y Superior Tijuana (CETYS University Tijuana)
 - level: International Baccalaureate Diploma (IB)
   date: 2017
   subject: Physics - Computing
   school: Preparatoria Federal Lázaro Cárdenas (CETYS University Tijuana)

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/specializations/algorithms
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
   talks:
    - title: Modeling, simulation and control of an autonomous quadrotor
      #speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
      conference: El Trompo Museo Interactivo Tijuana (Tijuana 2019)
    - title: Modeling, simulation and control of an autonomous quadrotor
      #speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
      conference: CINAP’s Research Seminar (Tijuana 2019)

#List of interesting Github repo/projects to include - optional
#github:
# - robhinds/robhinds.github.io
# - robhinds/ScaLambda
# - robhinds/opinionated-akka-http
# - robhinds/food2vec
# - robhinds/microservices
# - robhinds/spring-social-geeklist
# - robhinds/spring-social-stackoverflow
# - robhinds/genotype
# - robhinds/footweets
# - robhinds/ElasticSearchGradle

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  Mechatronics Engineering student at CETYS University Campus Tijuana and Research Engineer at CITEDI - IPN working on Neural Networks to predict the Glass Transition Temperature for Amorphous Metals.
  My objective is to implement tools such as Control Algorithms, Robotics and Artificial Intelligence to develop systems capable of solving real problems to improve quality of life for everyone. 

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong></strong>: <a target="_blank" href="https://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Test</a><br/><br/>
 
